--
-- Baseline: the schema as it stood when Hibernate still owned it.
--
-- Generated from the entity mappings, not dumped from a running database, so it says what the code
-- says rather than what one environment happened to contain. FlywayMigrationsMatchEntitiesTest
-- regenerates it on every build and fails if an entity has moved on without a migration.
--
-- Generated under Spring Boot's naming strategies, not Hibernate's bare defaults - that is the
-- difference between `recipient_id` and `recipientId`, and between the `task` table and `Task`.
-- Getting that wrong does not fail the build; it fails ddl-auto=validate on the first start, which
-- on Container Apps is a revision that never becomes healthy.
--
-- An environment whose schema Hibernate already created is baselined rather than re-created:
-- spring.flyway.baseline-on-migrate=true marks V1 as applied without running it, and migrations
-- above it take over from there. A fresh database is empty, so it runs V1 like any other.
--

create table chat_messages (
    id integer generated by default as identity,
    content TEXT,
    recipient_id varchar(255),
    room_id varchar(255),
    sender varchar(255),
    timestamp timestamp(6),
    type varchar(255) check (type in ('CHAT','JOIN','LEAVE','PRIVATE','NOTIFICATION')),
    primary key (id)
);

create table columns (
    id integer generated by default as identity,
    name varchar(255),
    position integer,
    wip_limit integer,
    primary key (id)
);

create table files (
    id bigint generated by default as identity,
    data oid,
    name varchar(255),
    type varchar(255),
    primary key (id)
);

create table rows (
    id integer generated by default as identity,
    name varchar(255),
    position integer,
    wip_limit integer,
    primary key (id)
);

create table subtasks (
    id integer generated by default as identity,
    completed boolean not null,
    description varchar(255),
    position integer,
    title TEXT,
    task_id integer,
    primary key (id)
);

create table task (
    id integer generated by default as identity,
    completed boolean not null,
    daily_focus boolean,
    deadline timestamp(6),
    description varchar(255),
    expired boolean,
    position integer,
    title varchar(255),
    column_id integer,
    parent_task_id integer,
    row_id integer,
    primary key (id)
);

create table task_column_history (
    id integer generated by default as identity,
    changed_at timestamp(6) not null,
    column_name varchar(255),
    history_order integer not null,
    column_id integer not null,
    task_id integer not null,
    primary key (id)
);

create table task_labels (
    task_id integer not null,
    label varchar(255)
);

create table user_task (
    task_id integer not null,
    user_id integer not null,
    primary key (task_id, user_id)
);

create table users (
    id integer generated by default as identity,
    email varchar(255) unique,
    enabled boolean not null,
    name varchar(255),
    password varchar(255),
    verification_code varchar(255),
    verification_expiration timestamp(6),
    wip_limit integer,
    avatar_id bigint unique,
    primary key (id)
);

--
-- Constraint names are Hibernate's own generated hashes, reproduced exactly. They derive from the
-- table and column names, so they are stable as long as those are - and an environment baselined
-- from ddl-auto=update already carries these exact names.
--
alter table if exists subtasks add constraint FKe8n02fhmb9ghmiart59asiyom foreign key (task_id) references task;
alter table if exists task add constraint FK2shyn87gxe74lli66rew41bwb foreign key (column_id) references columns;
alter table if exists task add constraint FKqxs9fnf0nvg4pou1gng0jtom4 foreign key (parent_task_id) references task;
alter table if exists task add constraint FKoh6t6u02q4jcvmbnc5ut0xvxu foreign key (row_id) references rows;
alter table if exists task_column_history add constraint FKrhtdcogd7sweikqvgo8vxdf3d foreign key (column_id) references columns;
alter table if exists task_column_history add constraint FKi4cdr6xe1nw4f4m8oy7hitwyu foreign key (task_id) references task;
alter table if exists task_labels add constraint FKia1qqvbp6d1xw3sod3xw1xpye foreign key (task_id) references task;
alter table if exists user_task add constraint FKj6lai3y87ttxldkysg1549etg foreign key (user_id) references users;
alter table if exists user_task add constraint FKvs34bjkmpbk2e54qlrol3ilt foreign key (task_id) references task;
alter table if exists users add constraint FKda0fl66rh9qsoty4s66xk29m6 foreign key (avatar_id) references files;
