--
-- Boards, and the membership that decides who can see one.
--
-- Until this migration there was no ownership anywhere in the schema: every column, row and task
-- belonged to the deployment rather than to anyone in it, so "authenticated" was the whole of the
-- authorization model. This adds the missing owner and points everything on the board at it.
--
-- The backfill has one job: leave an existing installation working exactly as it did. Everything
-- that is already there goes onto a single board and every account that already exists becomes a
-- member of it, which is precisely the arrangement those accounts had before - one shared board -
-- except that it is now written down and checked. Accounts created from here on get their own.
--
-- The board's owner is the oldest account, if there is one. On a fresh database there is not:
-- V3 seeds eight stages before anybody has signed up. That board is left with no owner, and
-- BoardService.provisionFor hands it to the first account that opens a board. The alternative -
-- inventing an owner in SQL - would either invent an account or strand those eight stages on a
-- board nobody could ever see.
--

CREATE TABLE boards (
    id         integer      GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(255) NOT NULL,
    owner_id   integer,
    created_at timestamp(6) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE board_members (
    board_id integer NOT NULL,
    user_id  integer NOT NULL,
    PRIMARY KEY (board_id, user_id)
);

ALTER TABLE boards
    ADD CONSTRAINT fk_boards_owner FOREIGN KEY (owner_id) REFERENCES users (id);
ALTER TABLE board_members
    ADD CONSTRAINT fk_board_members_board FOREIGN KEY (board_id) REFERENCES boards (id);
ALTER TABLE board_members
    ADD CONSTRAINT fk_board_members_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE columns ADD COLUMN board_id integer;
ALTER TABLE rows    ADD COLUMN board_id integer;
ALTER TABLE task    ADD COLUMN board_id integer;

-- The board is carried on the task itself and not read through its column, because a task can sit
-- in no column at all - and a task with no column would otherwise be a task with no owner.
ALTER TABLE files   ADD COLUMN owner_id integer;

--
-- One board for everything that is already here, and only if there is something to hold.
--
INSERT INTO boards (name, owner_id, created_at)
SELECT 'Kanban', (SELECT MIN(id) FROM users), CURRENT_TIMESTAMP
WHERE EXISTS (SELECT 1 FROM columns)
   OR EXISTS (SELECT 1 FROM rows)
   OR EXISTS (SELECT 1 FROM task);

UPDATE columns SET board_id = (SELECT MIN(id) FROM boards) WHERE board_id IS NULL;
UPDATE rows    SET board_id = (SELECT MIN(id) FROM boards) WHERE board_id IS NULL;
UPDATE task    SET board_id = (SELECT MIN(id) FROM boards) WHERE board_id IS NULL;

-- Everyone who already had access keeps it. Losing that would lock every existing account out of
-- the only board in the database.
INSERT INTO board_members (board_id, user_id)
SELECT (SELECT MIN(id) FROM boards), users.id
FROM users
WHERE EXISTS (SELECT 1 FROM boards);

-- An avatar is the one kind of file whose owner can be recovered: users.avatar_id already says so.
-- Anything else uploaded before this column existed stays unowned, and FileService reads an unowned
-- file as belonging to nobody rather than to everybody.
UPDATE files
SET owner_id = users.id
FROM users
WHERE users.avatar_id = files.id;

--
-- Only now, once nothing is left unassigned, does the column become mandatory. Doing it in the
-- other order would fail against any database that already has a board in it.
--
ALTER TABLE columns ALTER COLUMN board_id SET NOT NULL;
ALTER TABLE rows    ALTER COLUMN board_id SET NOT NULL;
ALTER TABLE task    ALTER COLUMN board_id SET NOT NULL;

ALTER TABLE columns
    ADD CONSTRAINT fk_columns_board FOREIGN KEY (board_id) REFERENCES boards (id);
ALTER TABLE rows
    ADD CONSTRAINT fk_rows_board FOREIGN KEY (board_id) REFERENCES boards (id);
ALTER TABLE task
    ADD CONSTRAINT fk_task_board FOREIGN KEY (board_id) REFERENCES boards (id);
ALTER TABLE files
    ADD CONSTRAINT fk_files_owner FOREIGN KEY (owner_id) REFERENCES users (id);

CREATE INDEX idx_columns_board ON columns (board_id);
CREATE INDEX idx_rows_board    ON rows (board_id);
CREATE INDEX idx_task_board    ON task (board_id);
