--
-- Refresh tokens: the first thing in this schema that can end a session.
--
-- A JWT is a signed claim, so nothing but its own expiry stops it. That made the one-hour lifetime
-- do two incompatible jobs at once - a hard cap on how long anyone could stay signed in, and the
-- only bound on a token somebody stole. This table separates them: the access token gets short
-- because losing it now costs minutes, and the session gets long because it is a row that can be
-- deleted.
--
-- token_hash, not the token. The reasoning is the one password_reset_code already follows: this
-- value is a credential, and the users table is exactly what an attacker with read access has. It
-- is SHA-256 hex, so 64 characters exactly - not a password hash, and deliberately not a slow one,
-- because the input is 256 bits of SecureRandom output and there is no dictionary to run against
-- it. UNIQUE because the digest is the lookup key on every refresh.
--
-- revoked_at rather than a DELETE. A spent row is what makes replay visible: a token presented
-- after it has been rotated means two parties hold the same chain, and RefreshTokenService reads
-- that as theft and withdraws the whole chain. Deleting the row would make that case
-- indistinguishable from a token that never existed.
--
-- ON DELETE CASCADE because a deleted account has no sessions to reason about, and the delete path
-- already exists (DELETE /api/users/{id}).
--

CREATE TABLE refresh_tokens (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY,
    token_hash varchar(64) NOT NULL,
    user_id    integer     NOT NULL,
    issued_at  timestamp(6) WITH TIME ZONE NOT NULL,
    expires_at timestamp(6) WITH TIME ZONE NOT NULL,
    revoked_at timestamp(6) WITH TIME ZONE,
    PRIMARY KEY (id)
);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash);
ALTER TABLE refresh_tokens
    ADD CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

-- Both of the reads this table takes: one row by digest on every refresh, and every live row for
-- one account when a password change withdraws them all.
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);

--
-- Nothing is backfilled, and nothing needs to be. Existing access tokens keep working until they
-- expire - there is no row that could have withdrawn them anyway - and the first login after this
-- deploys is what gives an account its first refresh token. The only visible effect on someone
-- already signed in is that their session ends at the old token's expiry instead of being renewed,
-- which is the same thing that happened to them yesterday.
--
